sudo: required
jdk: oraclejdk8

before_install: cd $HOME/.wurst

install:
  - wget http://peeeq.de/hudson/job/Wurst/lastSuccessfulBuild/artifact/downloads/wurstpack_compiler.zip
  - unzip -qq -n wurstpack_compiler.zip -d $HOME/.wurst

before_script: cd $HOME/.wurst

script:
  - java -jar wurstscript.jar common.j blizzard.j -runcompiletimefunctions -runtests
